/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTreeRouteImport } from './routes/_authenticated/tree'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedTreePersonIdRouteImport } from './routes/_authenticated/tree.$personId'
import { Route as AuthenticatedPersonPersonIdRouteImport } from './routes/_authenticated/person.$personId'
import { Route as AuthenticatedPersonPersonIdStoryEditRouteImport } from './routes/_authenticated/person.$personId_.story-edit'
import { Route as AuthenticatedPersonPersonIdStoryRouteImport } from './routes/_authenticated/person.$personId_.story'

const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTreeRoute = AuthenticatedTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTreePersonIdRoute =
  AuthenticatedTreePersonIdRouteImport.update({
    id: '/$personId',
    path: '/$personId',
    getParentRoute: () => AuthenticatedTreeRoute,
  } as any)
const AuthenticatedPersonPersonIdRoute =
  AuthenticatedPersonPersonIdRouteImport.update({
    id: '/person/$personId',
    path: '/person/$personId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonPersonIdStoryEditRoute =
  AuthenticatedPersonPersonIdStoryEditRouteImport.update({
    id: '/person/$personId_/story-edit',
    path: '/person/$personId/story-edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonPersonIdStoryRoute =
  AuthenticatedPersonPersonIdStoryRouteImport.update({
    id: '/person/$personId_/story',
    path: '/person/$personId/story',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/map': typeof AuthenticatedMapRoute
  '/media': typeof AuthenticatedMediaRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tree': typeof AuthenticatedTreeRouteWithChildren
  '/person/$personId': typeof AuthenticatedPersonPersonIdRoute
  '/tree/$personId': typeof AuthenticatedTreePersonIdRoute
  '/person/$personId/story': typeof AuthenticatedPersonPersonIdStoryRoute
  '/person/$personId/story-edit': typeof AuthenticatedPersonPersonIdStoryEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/map': typeof AuthenticatedMapRoute
  '/media': typeof AuthenticatedMediaRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tree': typeof AuthenticatedTreeRouteWithChildren
  '/person/$personId': typeof AuthenticatedPersonPersonIdRoute
  '/tree/$personId': typeof AuthenticatedTreePersonIdRoute
  '/person/$personId/story': typeof AuthenticatedPersonPersonIdStoryRoute
  '/person/$personId/story-edit': typeof AuthenticatedPersonPersonIdStoryEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tree': typeof AuthenticatedTreeRouteWithChildren
  '/_authenticated/person/$personId': typeof AuthenticatedPersonPersonIdRoute
  '/_authenticated/tree/$personId': typeof AuthenticatedTreePersonIdRoute
  '/_authenticated/person/$personId_/story': typeof AuthenticatedPersonPersonIdStoryRoute
  '/_authenticated/person/$personId_/story-edit': typeof AuthenticatedPersonPersonIdStoryEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/magic-link'
    | '/map'
    | '/media'
    | '/search'
    | '/settings'
    | '/tree'
    | '/person/$personId'
    | '/tree/$personId'
    | '/person/$personId/story'
    | '/person/$personId/story-edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/magic-link'
    | '/map'
    | '/media'
    | '/search'
    | '/settings'
    | '/tree'
    | '/person/$personId'
    | '/tree/$personId'
    | '/person/$personId/story'
    | '/person/$personId/story-edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password'
    | '/login'
    | '/magic-link'
    | '/_authenticated/map'
    | '/_authenticated/media'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/tree'
    | '/_authenticated/person/$personId'
    | '/_authenticated/tree/$personId'
    | '/_authenticated/person/$personId_/story'
    | '/_authenticated/person/$personId_/story-edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tree': {
      id: '/_authenticated/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof AuthenticatedTreeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tree/$personId': {
      id: '/_authenticated/tree/$personId'
      path: '/$personId'
      fullPath: '/tree/$personId'
      preLoaderRoute: typeof AuthenticatedTreePersonIdRouteImport
      parentRoute: typeof AuthenticatedTreeRoute
    }
    '/_authenticated/person/$personId': {
      id: '/_authenticated/person/$personId'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof AuthenticatedPersonPersonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/person/$personId_/story-edit': {
      id: '/_authenticated/person/$personId_/story-edit'
      path: '/person/$personId/story-edit'
      fullPath: '/person/$personId/story-edit'
      preLoaderRoute: typeof AuthenticatedPersonPersonIdStoryEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/person/$personId_/story': {
      id: '/_authenticated/person/$personId_/story'
      path: '/person/$personId/story'
      fullPath: '/person/$personId/story'
      preLoaderRoute: typeof AuthenticatedPersonPersonIdStoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedTreeRouteChildren {
  AuthenticatedTreePersonIdRoute: typeof AuthenticatedTreePersonIdRoute
}

const AuthenticatedTreeRouteChildren: AuthenticatedTreeRouteChildren = {
  AuthenticatedTreePersonIdRoute: AuthenticatedTreePersonIdRoute,
}

const AuthenticatedTreeRouteWithChildren =
  AuthenticatedTreeRoute._addFileChildren(AuthenticatedTreeRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTreeRoute: typeof AuthenticatedTreeRouteWithChildren
  AuthenticatedPersonPersonIdRoute: typeof AuthenticatedPersonPersonIdRoute
  AuthenticatedPersonPersonIdStoryRoute: typeof AuthenticatedPersonPersonIdStoryRoute
  AuthenticatedPersonPersonIdStoryEditRoute: typeof AuthenticatedPersonPersonIdStoryEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTreeRoute: AuthenticatedTreeRouteWithChildren,
  AuthenticatedPersonPersonIdRoute: AuthenticatedPersonPersonIdRoute,
  AuthenticatedPersonPersonIdStoryRoute: AuthenticatedPersonPersonIdStoryRoute,
  AuthenticatedPersonPersonIdStoryEditRoute:
    AuthenticatedPersonPersonIdStoryEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
