/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestAccessRouteImport } from './routes/request-access'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as MagicLinkRouteImport } from './routes/magic-link'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTreeRouteImport } from './routes/_authenticated/tree'
import { Route as AuthenticatedTraditionsRouteImport } from './routes/_authenticated/traditions'
import { Route as AuthenticatedStatsRouteImport } from './routes/_authenticated/stats'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedRelatedRouteImport } from './routes/_authenticated/related'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedTreePersonIdRouteImport } from './routes/_authenticated/tree.$personId'
import { Route as AuthenticatedPersonPersonIdRouteImport } from './routes/_authenticated/person.$personId'
import { Route as AuthenticatedAdminSignupRequestsRouteImport } from './routes/_authenticated/admin.signup-requests'
import { Route as AuthenticatedPersonPersonIdStoryEditRouteImport } from './routes/_authenticated/person.$personId_.story-edit'
import { Route as AuthenticatedPersonPersonIdStoryRouteImport } from './routes/_authenticated/person.$personId_.story'

const RequestAccessRoute = RequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MagicLinkRoute = MagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTreeRoute = AuthenticatedTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTraditionsRoute = AuthenticatedTraditionsRouteImport.update({
  id: '/traditions',
  path: '/traditions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatsRoute = AuthenticatedStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatedRoute = AuthenticatedRelatedRouteImport.update({
  id: '/related',
  path: '/related',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTreePersonIdRoute =
  AuthenticatedTreePersonIdRouteImport.update({
    id: '/$personId',
    path: '/$personId',
    getParentRoute: () => AuthenticatedTreeRoute,
  } as any)
const AuthenticatedPersonPersonIdRoute =
  AuthenticatedPersonPersonIdRouteImport.update({
    id: '/person/$personId',
    path: '/person/$personId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSignupRequestsRoute =
  AuthenticatedAdminSignupRequestsRouteImport.update({
    id: '/signup-requests',
    path: '/signup-requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPersonPersonIdStoryEditRoute =
  AuthenticatedPersonPersonIdStoryEditRouteImport.update({
    id: '/person/$personId_/story-edit',
    path: '/person/$personId/story-edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPersonPersonIdStoryRoute =
  AuthenticatedPersonPersonIdStoryRouteImport.update({
    id: '/person/$personId_/story',
    path: '/person/$personId/story',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/onboard': typeof OnboardRoute
  '/request-access': typeof RequestAccessRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/map': typeof AuthenticatedMapRoute
  '/media': typeof AuthenticatedMediaRoute
  '/related': typeof AuthenticatedRelatedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/traditions': typeof AuthenticatedTraditionsRoute
  '/tree': typeof AuthenticatedTreeRouteWithChildren
  '/admin/signup-requests': typeof AuthenticatedAdminSignupRequestsRoute
  '/person/$personId': typeof AuthenticatedPersonPersonIdRoute
  '/tree/$personId': typeof AuthenticatedTreePersonIdRoute
  '/person/$personId/story': typeof AuthenticatedPersonPersonIdStoryRoute
  '/person/$personId/story-edit': typeof AuthenticatedPersonPersonIdStoryEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/onboard': typeof OnboardRoute
  '/request-access': typeof RequestAccessRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/map': typeof AuthenticatedMapRoute
  '/media': typeof AuthenticatedMediaRoute
  '/related': typeof AuthenticatedRelatedRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/stats': typeof AuthenticatedStatsRoute
  '/traditions': typeof AuthenticatedTraditionsRoute
  '/tree': typeof AuthenticatedTreeRouteWithChildren
  '/admin/signup-requests': typeof AuthenticatedAdminSignupRequestsRoute
  '/person/$personId': typeof AuthenticatedPersonPersonIdRoute
  '/tree/$personId': typeof AuthenticatedTreePersonIdRoute
  '/person/$personId/story': typeof AuthenticatedPersonPersonIdStoryRoute
  '/person/$personId/story-edit': typeof AuthenticatedPersonPersonIdStoryEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/magic-link': typeof MagicLinkRoute
  '/onboard': typeof OnboardRoute
  '/request-access': typeof RequestAccessRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/related': typeof AuthenticatedRelatedRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/stats': typeof AuthenticatedStatsRoute
  '/_authenticated/traditions': typeof AuthenticatedTraditionsRoute
  '/_authenticated/tree': typeof AuthenticatedTreeRouteWithChildren
  '/_authenticated/admin/signup-requests': typeof AuthenticatedAdminSignupRequestsRoute
  '/_authenticated/person/$personId': typeof AuthenticatedPersonPersonIdRoute
  '/_authenticated/tree/$personId': typeof AuthenticatedTreePersonIdRoute
  '/_authenticated/person/$personId_/story': typeof AuthenticatedPersonPersonIdStoryRoute
  '/_authenticated/person/$personId_/story-edit': typeof AuthenticatedPersonPersonIdStoryEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/login'
    | '/magic-link'
    | '/onboard'
    | '/request-access'
    | '/admin'
    | '/home'
    | '/map'
    | '/media'
    | '/related'
    | '/search'
    | '/settings'
    | '/stats'
    | '/traditions'
    | '/tree'
    | '/admin/signup-requests'
    | '/person/$personId'
    | '/tree/$personId'
    | '/person/$personId/story'
    | '/person/$personId/story-edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/login'
    | '/magic-link'
    | '/onboard'
    | '/request-access'
    | '/admin'
    | '/home'
    | '/map'
    | '/media'
    | '/related'
    | '/search'
    | '/settings'
    | '/stats'
    | '/traditions'
    | '/tree'
    | '/admin/signup-requests'
    | '/person/$personId'
    | '/tree/$personId'
    | '/person/$personId/story'
    | '/person/$personId/story-edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/change-password'
    | '/login'
    | '/magic-link'
    | '/onboard'
    | '/request-access'
    | '/_authenticated/admin'
    | '/_authenticated/home'
    | '/_authenticated/map'
    | '/_authenticated/media'
    | '/_authenticated/related'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/stats'
    | '/_authenticated/traditions'
    | '/_authenticated/tree'
    | '/_authenticated/admin/signup-requests'
    | '/_authenticated/person/$personId'
    | '/_authenticated/tree/$personId'
    | '/_authenticated/person/$personId_/story'
    | '/_authenticated/person/$personId_/story-edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  MagicLinkRoute: typeof MagicLinkRoute
  OnboardRoute: typeof OnboardRoute
  RequestAccessRoute: typeof RequestAccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request-access': {
      id: '/request-access'
      path: '/request-access'
      fullPath: '/request-access'
      preLoaderRoute: typeof RequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magic-link': {
      id: '/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof MagicLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tree': {
      id: '/_authenticated/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof AuthenticatedTreeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/traditions': {
      id: '/_authenticated/traditions'
      path: '/traditions'
      fullPath: '/traditions'
      preLoaderRoute: typeof AuthenticatedTraditionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/stats': {
      id: '/_authenticated/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AuthenticatedStatsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/related': {
      id: '/_authenticated/related'
      path: '/related'
      fullPath: '/related'
      preLoaderRoute: typeof AuthenticatedRelatedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tree/$personId': {
      id: '/_authenticated/tree/$personId'
      path: '/$personId'
      fullPath: '/tree/$personId'
      preLoaderRoute: typeof AuthenticatedTreePersonIdRouteImport
      parentRoute: typeof AuthenticatedTreeRoute
    }
    '/_authenticated/person/$personId': {
      id: '/_authenticated/person/$personId'
      path: '/person/$personId'
      fullPath: '/person/$personId'
      preLoaderRoute: typeof AuthenticatedPersonPersonIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/signup-requests': {
      id: '/_authenticated/admin/signup-requests'
      path: '/signup-requests'
      fullPath: '/admin/signup-requests'
      preLoaderRoute: typeof AuthenticatedAdminSignupRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/person/$personId_/story-edit': {
      id: '/_authenticated/person/$personId_/story-edit'
      path: '/person/$personId/story-edit'
      fullPath: '/person/$personId/story-edit'
      preLoaderRoute: typeof AuthenticatedPersonPersonIdStoryEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/person/$personId_/story': {
      id: '/_authenticated/person/$personId_/story'
      path: '/person/$personId/story'
      fullPath: '/person/$personId/story'
      preLoaderRoute: typeof AuthenticatedPersonPersonIdStoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminSignupRequestsRoute: typeof AuthenticatedAdminSignupRequestsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminSignupRequestsRoute: AuthenticatedAdminSignupRequestsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedTreeRouteChildren {
  AuthenticatedTreePersonIdRoute: typeof AuthenticatedTreePersonIdRoute
}

const AuthenticatedTreeRouteChildren: AuthenticatedTreeRouteChildren = {
  AuthenticatedTreePersonIdRoute: AuthenticatedTreePersonIdRoute,
}

const AuthenticatedTreeRouteWithChildren =
  AuthenticatedTreeRoute._addFileChildren(AuthenticatedTreeRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedRelatedRoute: typeof AuthenticatedRelatedRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStatsRoute: typeof AuthenticatedStatsRoute
  AuthenticatedTraditionsRoute: typeof AuthenticatedTraditionsRoute
  AuthenticatedTreeRoute: typeof AuthenticatedTreeRouteWithChildren
  AuthenticatedPersonPersonIdRoute: typeof AuthenticatedPersonPersonIdRoute
  AuthenticatedPersonPersonIdStoryRoute: typeof AuthenticatedPersonPersonIdStoryRoute
  AuthenticatedPersonPersonIdStoryEditRoute: typeof AuthenticatedPersonPersonIdStoryEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedRelatedRoute: AuthenticatedRelatedRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStatsRoute: AuthenticatedStatsRoute,
  AuthenticatedTraditionsRoute: AuthenticatedTraditionsRoute,
  AuthenticatedTreeRoute: AuthenticatedTreeRouteWithChildren,
  AuthenticatedPersonPersonIdRoute: AuthenticatedPersonPersonIdRoute,
  AuthenticatedPersonPersonIdStoryRoute: AuthenticatedPersonPersonIdStoryRoute,
  AuthenticatedPersonPersonIdStoryEditRoute:
    AuthenticatedPersonPersonIdStoryEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  MagicLinkRoute: MagicLinkRoute,
  OnboardRoute: OnboardRoute,
  RequestAccessRoute: RequestAccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
